version: '2.1'
services:
  app:
    build: ./
    privileged: true
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
      - UDEV=1
    labels:
      io.balena.features.dbus: '1'
    restart: always
