version: '2.1'
services:
  pigpiod:
    image: balenalib/raspberrypi4-64-node:16.19.1-buster
    command: pigpiod -g
    restart: always

  app:
    build: ./
    privileged: true
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
      - UDEV=1
    labels:
      io.balena.features.dbus: '1'
    restart: always
    depends_on:
      - pigpiod
